#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

msg="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

if [ $# -le 4 ]
    then
    echo $msg
else
    echo 'scp -i "$1" "$2" "$3" "$4"'
fi
