#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

msg="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

if [ $# -le 3 ]
    then
    echo "$msg"
else
    scp -i "$4" "$1" "$3""@""$2":~/
fi
