#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

msg="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

if [ $# != 4 ]
    then
    echo "$msg"
else
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3""@""$2":~/
fi
