#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i "/server_name _;/a rewrite ^/redirect_me https://twitter.com/Yulyzulu5 permanent;" /etc/nginx/sites-available/default
sudo service nginx start
