#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i "/server_name _;/a rewrite ^/redirect_me https://twitter.com/Yulyzulu5 permanent;" /etc/nginx/sites-available/default
#Create new page custom
#Configure custom page
sudo service nginx restart
