#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i "/server_name _;/a rewrite ^/redirect_me https://twitter.com/Yulyzulu5 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page\n" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "35 a \ \n \t error_page 404 /custom_404; \n\t location = /custom_404.html {\n\t\t root /usr/share/nginx/html; \n\t\t internal;\n\t}" /etc/nginx/sites-enabled/default
sudo service nginx restart
