#!/usr/bin/env bash
# This script displays msgs, sleep and receiving a SIGTERM signal

trap 'echo I am invincible!!!' SIGTERM 

msg="To infinity and beyond"

while ((1))
do
    echo "$msg"
    sleep 2
done    
