#!/usr/bin/env bash
# This script that gives information about the holbertonschool file

file="holbertonschool"

if [ -e "$file" ]
then
    echo "$file file exists"

    if [ -s "$file" ]
    then
        echo "$file file is not empty"
    else
        echo "$file file is empty"
    fi

    if [ -f "$file" ]
    then
        echo "$file file a regular file"
    fi

else
    echo "$file file does not exist"
fi
