#!/usr/bin/env bash
# Script that change the user root to nginx
sudo pkill apache2
sudo sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
sudo chmod 777 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
